mod collecton;
mod comment_doc;
pub mod compound_types;
mod crate_module;
mod flow_control;
mod function;
mod generics_trait;
mod lifetime;
mod method;
mod ownership_borrowing;
mod pattern_match;
pub mod primitive_types;
mod return_panic;
mod string_str;
pub mod variable;
