mod collecton;
mod compound_types;
mod flow_control;
mod function;
mod generics_trait;
mod method;
mod ownership_borrowing;
mod pattern_match;
pub mod primitive_types;
mod string_str;
pub mod variable;
